apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"chaos-mesh.org/v1alpha1","kind":"StressChaos","metadata":{"annotations":{},"labels":{"scenario":"sf-002","tier":"single_fault"},"name":"sf-002-paymentservice-cpu","namespace":"chaos-mesh"},"spec":{"duration":"10m","mode":"one","selector":{"labelSelectors":{"app":"paymentservice"},"namespaces":["default"]},"stressors":{"cpu":{"load":90,"workers":4}}}}
  creationTimestamp: "2026-08-29T08:40:15Z"
  finalizers:
  - chaos-mesh/records
  generation: 8
  labels:
    scenario: sf-002
    tier: single_fault
  name: sf-002-paymentservice-cpu
  namespace: chaos-mesh
  resourceVersion: "598813"
  uid: f0b58735-f333-46f5-8a98-132096554c44
spec:
  duration: 10m
  mode: one
  selector:
    labelSelectors:
      app: paymentservice
    namespaces:
    - default
  stressors:
    cpu:
      load: 90
      workers: 4
status:
  conditions:
  - status: "True"
    type: Selected
  - status: "False"
    type: AllInjected
  - status: "True"
    type: AllRecovered
  - status: "False"
    type: Paused
  experiment:
    containerRecords:
    - events:
      - operation: Apply
        timestamp: "2026-08-29T08:40:16Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-08-29T08:50:33Z"
        type: Succeeded
      id: default/paymentservice-657564d676-cgmgw/server
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .
    desiredPhase: Stop
